# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.get.loss.cpp.internal <- function(X, y, w) {
    .Call('_gumbelRegression_get_loss', PACKAGE = 'gumbelRegression', X, y, w)
}

.test.loss.cpp <- function(X, y, w0, w, lossType) {
    .Call('_gumbelRegression_test_loss', PACKAGE = 'gumbelRegression', X, y, w0, w, lossType)
}

.get.gradient.cpp.internal <- function(X, y, w) {
    .Call('_gumbelRegression_get_gradient', PACKAGE = 'gumbelRegression', X, y, w)
}

.test.gradient.cpp <- function(X, y, w0, w, lossType) {
    .Call('_gumbelRegression_test_gradient', PACKAGE = 'gumbelRegression', X, y, w0, w, lossType)
}

.get.Hv.cpp.internal <- function(X, y, w, v) {
    .Call('_gumbelRegression_get_Hv', PACKAGE = 'gumbelRegression', X, y, w, v)
}

.test.Hv.cpp <- function(X, y, w0, w, v, lossType) {
    .Call('_gumbelRegression_test_Hv', PACKAGE = 'gumbelRegression', X, y, w0, w, v, lossType)
}

.gumbelRegression.cpp.internal <- function(X, y, foldId, lambdaSeq, tolerance) {
    .Call('_gumbelRegression_gumbelRegressionCpp', PACKAGE = 'gumbelRegression', X, y, foldId, lambdaSeq, tolerance)
}

